In [35]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import os

from scipy import stats
from scipy.stats import norm, ttest_ind, shapiro

In [36]:
path = "C:\\Users\\Quyntrd\\Desktop\\MatStat\\3"
os.chdir(path)

CFD = pd.read_excel("CHISLO_DOCTORS.xlsx", sheet_name='ROSSTAT')

CFD = CFD.iloc[90:101]
CFD = CFD.iloc[:, :13]
CFD = CFD.drop(CFD.columns[[1,2,3,4,5,6]], axis=1)
CFD.columns = ['Название области', '2005', '2010', '2015','2019', '2020', '2021']
CFD.set_index('Название области', inplace=True)

CFD = CFD.astype(float).copy()

data = []
for i in range(len(CFD.columns)):
    for j in range (len(CFD.iloc[:, i])):
        data.append(CFD.iloc[j,i])
print(data)

[38.6, 49.3, 52.5, 53.2, 53.5, 60.5, 60.7, 55.2, 44.0, 37.0, 78.8, 41.3, 57.1, 56.1, 49.3, 52.7, 61.1, 62.8, 55.6, 49.1, 35.4, 76.7, 45.6, 55.2, 48.8, 53.6, 50.0, 53.5, 55.4, 61.0, 54.1, 37.9, 65.0, 45.1, 61.6, 50.9, 52.9, 51.8, 56.4, 54.9, 62.2, 63.6, 38.0, 71.0, 44.7, 60.3, 52.3, 52.5, 51.1, 57.5, 55.4, 62.4, 64.6, 37.6, 73.7, 43.4, 60.0, 50.9, 54.9, 50.8, 56.4, 56.8, 63.1, 65.5, 35.2, 74.1]


In [37]:
ALPHA = 0.025  # Уровень значимости

# Проведение теста Шапиро-Уилка
stat, p_value = stats.shapiro(data)
# Вывод результатов
print(f"Результаты теста Шапиро-Уилка - :")
print(f"Статистика теста: {stat:.4f}")
print(f"P-значение: {p_value:.4f}")
# Проверка гипотезы
# H0: CFD - normal distribution
# H1: CFD - NOT normal distribution
if p_value > ALPHA:
    print(f"Гипотеза о нормальности НЕ отвергается на уровне значимости {ALPHA}.")
    print("Распределение можно считать нормальным.")
else:
    print(f"Гипотеза о нормальности отвергается на уровне значимости {ALPHA}.")
    print("Распределение нельзя считать нормальным.")

print("\n")



Результаты теста Шапиро-Уилка - :
Статистика теста: 0.9724
P-значение: 0.1474
Гипотеза о нормальности НЕ отвергается на уровне значимости 0.025.
Распределение можно считать нормальным.




In [98]:
observed_freq, bins = np.histogram(data, bins=6, density=False)
print(observed_freq)
# Ожидаемая частота для нормального распределения
mean, std = np.mean(data), np.std(data)
observed_freq[4] += observed_freq[5]
observed_freq = observed_freq[:5]
print(observed_freq)
# Для нормального распределения рассчитываем вероятность попадания в каждый интервал
expected_freq = len(data) * (stats.norm.cdf(bins[1:], loc=mean, scale=std) - stats.norm.cdf(bins[:-1], loc=mean, scale=std))
print(expected_freq)

# Нормализуем ожидаемые частоты, чтобы их сумма совпала с наблюдаемыми
scale_factor = np.sum(observed_freq) / np.sum(expected_freq)
expected_freq = (expected_freq * scale_factor).round()
print(expected_freq)
expected_freq[4] += expected_freq[5]
expected_freq = expected_freq[:5]
print(expected_freq)
# Применяем критерий хи-квадрат
chi2_stat, p_value = stats.chisquare(observed_freq, expected_freq)
# Вывод результатов
print(f"Результаты теста хи-квадрат -:")
print(f"Статистика теста: {chi2_stat:.4f}")
print(f"P-значение: {p_value:.4f}")
# Проверка гипотезы
if p_value > ALPHA:
    print(f"Гипотеза о нормальности НЕ отвергается на уровне значимости {ALPHA}.")
    print("Распределение можно считать нормальным.")
else:
    print(f"Гипотеза о нормальности отвергается на уровне значимости {ALPHA}.")
    print("Распределение нельзя считать нормальным.")

print("\n")

[ 8  9 27 14  4  4]
[ 8  9 27 14  8]
[ 5.55359102 13.58798483 19.30043897 15.92344131  7.62850056  2.11989754]
[ 6. 14. 20. 16.  8.  2.]
[ 6. 14. 20. 16. 10.]
Результаты теста хи-квадрат -:
Статистика теста: 5.5524
P-значение: 0.2352
Гипотеза о нормальности НЕ отвергается на уровне значимости 0.025.
Распределение можно считать нормальным.




In [39]:
ALPHA = 0.025  # Уровень значимости
# Проведение теста Шапиро-Уилка
stat, p_value = stats.normaltest(data)
# Вывод результатов
print(f"Результаты теста Шапиро-Уилка -:")
print(f"Статистика теста: {stat}")
print(f"P-значение: {p_value}")
# Проверка гипотезы
# H0: CFD - normal distribution
# H1: CFD - NOT normal distribution
if p_value > ALPHA:
    print(f"Гипотеза о нормальности НЕ отвергается на уровне значимости {ALPHA}.")
    print("Распределение можно считать нормальным.")
else:
    print(f"Гипотеза о нормальности отвергается на уровне значимости {ALPHA}.")
    print("Распределение нельзя считать нормальным.")
print("\n")

Результаты теста Шапиро-Уилка -:
Статистика теста: 0.6138429116824939
P-значение: 0.7357083842340795
Гипотеза о нормальности НЕ отвергается на уровне значимости 0.025.
Распределение можно считать нормальным.




In [40]:
M = 6500       # Количество выборок
a = -3         # Среднее значение
sigma = 6      # Стандартное отклонение
alpha = 0.025  # Уровень значимости
n = 45         # Размер выборки

shapiro_rejections = 0
dagostino_rejections = 0

In [41]:
for _ in range(M):
    sample = np.random.normal(a, sigma, n)
    
    stat_shapiro, p_value_shapiro = stats.shapiro(sample)
    if p_value_shapiro < alpha:
        shapiro_rejections += 1
    
    stat_dagostino, p_value_dagostino = stats.normaltest(sample)
    if p_value_dagostino < alpha:
        dagostino_rejections += 1

In [42]:
error_rate_shapiro = shapiro_rejections / M
error_rate_dagostino = dagostino_rejections / M

In [43]:
print(f"Оценка вероятности ошибки первого рода для теста Шапиро-Уилка: {error_rate_shapiro:.4f}")
print(f"Оценка вероятности ошибки первого рода для теста Д’Агостино: {error_rate_dagostino:.4f}")

Оценка вероятности ошибки первого рода для теста Шапиро-Уилка: 0.0235
Оценка вероятности ошибки первого рода для теста Д’Агостино: 0.0342


In [44]:
M = 6500       # Количество выборок
k = 8          # Число степеней свободы
alpha = 0.025  # Уровень значимости
n = 45         # Размер выборки

shapiro_rejections = 0
dagostino_rejections = 0

In [45]:
for _ in range(M):
    sample = np.random.standard_t(k, n)

    stat_shapiro, p_value_shapiro = stats.shapiro(sample)
    if p_value_shapiro < alpha:
        shapiro_rejections += 1
    
    stat_dagostino, p_value_dagostino = stats.normaltest(sample)
    if p_value_dagostino < alpha:
        dagostino_rejections += 1

In [46]:
power_shapiro = shapiro_rejections / M
power_dagostino = dagostino_rejections / M

In [47]:
print(f"Оценка мощности теста Шапиро-Уилка: {power_shapiro:.4f}")
print(f"Оценка мощности теста Д’Агостино: {power_dagostino:.4f}")

Оценка мощности теста Шапиро-Уилка: 0.1382
Оценка мощности теста Д’Агостино: 0.1852


In [48]:
if power_shapiro > power_dagostino:
    print("Тест Шапиро-Уилка более мощный при данной альтернативе.")
else:
    print("Тест Д’Агостино более мощный при данной альтернативе.")

Тест Д’Агостино более мощный при данной альтернативе.
